-- Enable extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

-- Set timezone
SET TIMEZONE TO 'UTC';
ALTER DATABASE lumi SET TIMEZONE TO 'UTC';
